[assets.image]
repo = "ghcr.io/fj0r"
dest = '~/pub/Platform'

tags = [
  "latest",
  "rust",
  "z",
  "marimo",
  "ci",
  # "haskell",
  "sid",
  "ferron",
  # vessel
  "surreal",
  "mihomo",
]
[assets.image.manifest.io]
xy = [
    "latest",
    "z",
    "rust",
]

[assets.image.manifest.vessel]
xy = ["vessel"]

[assets.image.manifest.ferron]
xy = ["sid", "ferron"]

[assets.image.manifest.pg18]
pg = [
    "18",
    "18gis",
]

[assets.image.manifest.surreal]
xy = ["surreal"]

#[assets.image.manifest.php]
#0x = [
#    "openresty",
#    "php7",
#    "php72",
#    "php8",
#]

#[assets.image.manifest.java]
#0x = ["java17"]

[assets.image.manifest.vpn]
0x = [
    "wg",
    "warpgate",
]

[assets.image.manifest.typst]
0x = ["typst"]

#[manifest.pyflink]
#0x = ["pyflink"]

[assets.image.manifest.llm]
xy = ["ollama"]

[assets.image.manifest.marimo]
xy = ["marimo"]
