[assets.image]
repo = "ghcr.io/fj0r"
dest = '~/pub/Platform'

[assets.image.manifest.xy]
xy = [
    "latest",
    "rust",
    "haskell",
    # "moon",
]

[assets.image.manifest.py]
xy = ["deb", "py"]

[assets.image.manifest.marimo]
xy = ["marimo"]

[assets.image.manifest.ci]
xy = ["ci"]

[assets.image.manifest.mihomo]
xy = ["mihomo"]

[assets.image.manifest.vessel]
xy = ["ferron", "vessel", "box"]

[assets.image.manifest.surreal]
xy = ["surreal"]

[assets.image.manifest.pg]
xy = [
    "postgres",
    # "18gis",
]

[assets.image.manifest.llm]
xy = ["ollama"]

[assets.image.manifest.agents]
xy = ["hermes"]

#[assets.image.manifest.php]
#0x = [
#    "php7",
#    "php8",
#]

#[assets.image.manifest.java]
#0x = ["java17"]

[assets.image.manifest.vpn]
xy = ["wireguard", "warpgate", "easytier"]

#[manifest.pyflink]
#0x = ["pyflink"]
