*:8080 {
  root "/srv"
  cgi {
  }
  rewrite "^/bin(.*)" "/ferron/bin.nu$1" {
    file true
    directory true
    last true
  }
  rewrite "^/box(.*)" "/ferron/box.nu$1" {
    file true
    directory true
    last true
  }
  rewrite "^/vessel(.*)" "/ferron/vessel.nu$1" {
    file true
    directory true
    last true
  }
  rewrite "^/(.*)" "/ferron/index.nu/$1" {
    file true
    directory true
    last true
  }
  cgi {
    extension ".nu"
    environment "BOX_PREFIX" "/box"
  }
  observability {
    provider "file"
    access_log "/dev/stdout"
  }
  observability {
    provider "file"
    error_log "/dev/stderr"
  }
}