*:8080 {
  root "/srv"
  rewrite "^/(.*)" "/index.php/$1" {
    file false
    directory false
  }
  fcgi_php "unix:///var/run/php/php-fpm.sock"
  observability {
    provider "file"
    access_log "/dev/stdout"
  }
  observability {
    provider "file"
    error_log "/dev/stderr"
  }
}
