name: branch_base
on:
  push:
    branches:
    - base
    tags:
    - v*.*.*
  workflow_dispatch: null
env:
  REGISTRY: ghcr.io
  USERNAME: fj0r
  IMAGE_NAME: xy
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !endsWith(github.event.head_commit.message, '~') }}
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    - name: Setup Nushell
      uses: hustcer/setup-nu@v3
      with:
        version: 0.109.1
    - name: Setup upterm session
      uses: owenthereal/action-upterm@v1
      if: contains(github.event.head_commit.message, '+debug')
      with:
        upterm-server: ${{ secrets.UPTERMD_ADDR }}
    - name: build base
      shell: buildah unshare nu {0}
      run: |-
        overlay use ${{ github.workspace }}/images/core/base.nu as build
        build {
          author: ${{ env.USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
          image: ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}
          tags: base
        }
